<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkflowStageSeeder extends Seeder
{
    /**
     * Default 21-stage workflow for fashion/tailoring orders
     */
    public function run(): void
    {
        // This seeder creates template data
        // Actual tenant data will be created when a new tenant registers

        $stages = [
            [
                'stage_order' => 1,
                'code' => 'ORDER_RECEIVED',
                'name' => 'Order Received',
                'name_gujarati' => 'ઓર્ડર પ્રાપ્ત',
                'name_hindi' => 'ऑर्डर प्राप्त',
                'description' => 'Order has been placed and confirmed',
                'color' => '#6366f1',
                'icon' => 'clipboard-check',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => true,
                'estimated_days' => 0,
                'assigned_role' => 'staff',
            ],
            [
                'stage_order' => 2,
                'code' => 'MEASUREMENT_CONFIRMED',
                'name' => 'Measurement Confirmed',
                'name_gujarati' => 'માપ કન્ફર્મ',
                'name_hindi' => 'माप कन्फर्म',
                'description' => 'Customer measurements have been verified',
                'color' => '#8b5cf6',
                'icon' => 'ruler',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 1,
                'assigned_role' => 'staff',
            ],
            [
                'stage_order' => 3,
                'code' => 'FABRIC_SELECTION',
                'name' => 'Fabric Selection',
                'name_gujarati' => 'કાપડ પસંદગી',
                'name_hindi' => 'कपड़ा चयन',
                'description' => 'Fabric has been selected/sourced',
                'color' => '#a855f7',
                'icon' => 'squares-2x2',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => true,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 2,
                'assigned_role' => 'staff',
            ],
            [
                'stage_order' => 4,
                'code' => 'FABRIC_RECEIVED',
                'name' => 'Fabric Received',
                'name_gujarati' => 'કાપડ પ્રાપ્ત',
                'name_hindi' => 'कपड़ा प्राप्त',
                'description' => 'Fabric has been received in workshop',
                'color' => '#c026d3',
                'icon' => 'inbox-arrow-down',
                'is_mandatory' => true,
                'is_skippable' => true,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 1,
                'assigned_role' => 'staff',
            ],
            [
                'stage_order' => 5,
                'code' => 'CUTTING',
                'name' => 'Cutting',
                'name_gujarati' => 'કટિંગ',
                'name_hindi' => 'कटिंग',
                'description' => 'Fabric cutting in progress',
                'color' => '#db2777',
                'icon' => 'scissors',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 1,
                'assigned_role' => 'worker',
            ],
            [
                'stage_order' => 6,
                'code' => 'CUTTING_COMPLETE',
                'name' => 'Cutting Complete',
                'name_gujarati' => 'કટિંગ પૂર્ણ',
                'name_hindi' => 'कटिंग पूर्ण',
                'description' => 'Fabric cutting has been completed',
                'color' => '#e11d48',
                'icon' => 'check-circle',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => true,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 0,
                'assigned_role' => 'worker',
            ],
            [
                'stage_order' => 7,
                'code' => 'EMBROIDERY_ASSIGNED',
                'name' => 'Embroidery Assigned',
                'name_gujarati' => 'ભરતકામ સોંપ્યું',
                'name_hindi' => 'कढ़ाई सौंपी',
                'description' => 'Embroidery work assigned to artisan',
                'color' => '#f97316',
                'icon' => 'sparkles',
                'is_mandatory' => false,
                'is_skippable' => true,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 1,
                'assigned_role' => 'manager',
            ],
            [
                'stage_order' => 8,
                'code' => 'EMBROIDERY_IN_PROGRESS',
                'name' => 'Embroidery In Progress',
                'name_gujarati' => 'ભરતકામ ચાલુ',
                'name_hindi' => 'कढ़ाई जारी',
                'description' => 'Embroidery/embellishment work in progress',
                'color' => '#fb923c',
                'icon' => 'cog',
                'is_mandatory' => false,
                'is_skippable' => true,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 5,
                'assigned_role' => 'worker',
            ],
            [
                'stage_order' => 9,
                'code' => 'EMBROIDERY_COMPLETE',
                'name' => 'Embroidery Complete',
                'name_gujarati' => 'ભરતકામ પૂર્ણ',
                'name_hindi' => 'कढ़ाई पूर्ण',
                'description' => 'Embroidery/embellishment work completed',
                'color' => '#fbbf24',
                'icon' => 'check-badge',
                'is_mandatory' => false,
                'is_skippable' => true,
                'requires_photo' => true,
                'requires_approval' => true,
                'notify_customer' => false,
                'estimated_days' => 0,
                'assigned_role' => 'worker',
            ],
            [
                'stage_order' => 10,
                'code' => 'STITCHING_ASSIGNED',
                'name' => 'Stitching Assigned',
                'name_gujarati' => 'સિલાઈ સોંપી',
                'name_hindi' => 'सिलाई सौंपी',
                'description' => 'Stitching work assigned to tailor',
                'color' => '#84cc16',
                'icon' => 'user-plus',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 1,
                'assigned_role' => 'manager',
            ],
            [
                'stage_order' => 11,
                'code' => 'STITCHING_IN_PROGRESS',
                'name' => 'Stitching In Progress',
                'name_gujarati' => 'સિલાઈ ચાલુ',
                'name_hindi' => 'सिलाई जारी',
                'description' => 'Garment stitching in progress',
                'color' => '#22c55e',
                'icon' => 'cog',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 3,
                'assigned_role' => 'worker',
            ],
            [
                'stage_order' => 12,
                'code' => 'STITCHING_COMPLETE',
                'name' => 'Stitching Complete',
                'name_gujarati' => 'સિલાઈ પૂર્ણ',
                'name_hindi' => 'सिलाई पूर्ण',
                'description' => 'Garment stitching completed',
                'color' => '#10b981',
                'icon' => 'check-circle',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => true,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 0,
                'assigned_role' => 'worker',
            ],
            [
                'stage_order' => 13,
                'code' => 'FIRST_FITTING',
                'name' => 'First Fitting',
                'name_gujarati' => 'પ્રથમ ફિટિંગ',
                'name_hindi' => 'पहली फिटिंग',
                'description' => 'First trial fitting with customer',
                'color' => '#14b8a6',
                'icon' => 'user-check',
                'is_mandatory' => false,
                'is_skippable' => true,
                'requires_photo' => true,
                'requires_approval' => true,
                'notify_customer' => true,
                'estimated_days' => 1,
                'assigned_role' => 'staff',
            ],
            [
                'stage_order' => 14,
                'code' => 'ALTERATIONS',
                'name' => 'Alterations',
                'name_gujarati' => 'ફેરફાર',
                'name_hindi' => 'बदलाव',
                'description' => 'Alterations based on fitting feedback',
                'color' => '#06b6d4',
                'icon' => 'wrench',
                'is_mandatory' => false,
                'is_skippable' => true,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 2,
                'assigned_role' => 'worker',
            ],
            [
                'stage_order' => 15,
                'code' => 'FINAL_FITTING',
                'name' => 'Final Fitting',
                'name_gujarati' => 'અંતિમ ફિટિંગ',
                'name_hindi' => 'अंतिम फिटिंग',
                'description' => 'Final fitting and approval',
                'color' => '#0ea5e9',
                'icon' => 'clipboard-check',
                'is_mandatory' => false,
                'is_skippable' => true,
                'requires_photo' => true,
                'requires_approval' => true,
                'notify_customer' => true,
                'estimated_days' => 1,
                'assigned_role' => 'staff',
            ],
            [
                'stage_order' => 16,
                'code' => 'FINISHING',
                'name' => 'Finishing',
                'name_gujarati' => 'ફિનિશિંગ',
                'name_hindi' => 'फिनिशिंग',
                'description' => 'Final finishing touches',
                'color' => '#3b82f6',
                'icon' => 'sparkles',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 1,
                'assigned_role' => 'worker',
            ],
            [
                'stage_order' => 17,
                'code' => 'QUALITY_CHECK',
                'name' => 'Quality Check',
                'name_gujarati' => 'ક્વોલિટી ચેક',
                'name_hindi' => 'क्वालिटी चेक',
                'description' => 'Final quality inspection',
                'color' => '#6366f1',
                'icon' => 'shield-check',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => true,
                'requires_approval' => true,
                'notify_customer' => false,
                'estimated_days' => 1,
                'assigned_role' => 'manager',
            ],
            [
                'stage_order' => 18,
                'code' => 'IRONING_PRESSING',
                'name' => 'Ironing & Pressing',
                'name_gujarati' => 'ઈસ્ત્રી',
                'name_hindi' => 'इस्त्री',
                'description' => 'Final pressing and ironing',
                'color' => '#8b5cf6',
                'icon' => 'fire',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 1,
                'assigned_role' => 'worker',
            ],
            [
                'stage_order' => 19,
                'code' => 'PACKING',
                'name' => 'Packing',
                'name_gujarati' => 'પેકિંગ',
                'name_hindi' => 'पैकिंग',
                'description' => 'Garment packed and ready',
                'color' => '#a855f7',
                'icon' => 'gift',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => true,
                'requires_approval' => false,
                'notify_customer' => false,
                'estimated_days' => 0,
                'assigned_role' => 'staff',
            ],
            [
                'stage_order' => 20,
                'code' => 'READY_FOR_DELIVERY',
                'name' => 'Ready for Delivery',
                'name_gujarati' => 'ડિલિવરી માટે તૈયાર',
                'name_hindi' => 'डिलीवरी के लिए तैयार',
                'description' => 'Order ready for customer pickup/delivery',
                'color' => '#c026d3',
                'icon' => 'truck',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => true,
                'estimated_days' => 0,
                'assigned_role' => 'staff',
            ],
            [
                'stage_order' => 21,
                'code' => 'DELIVERED',
                'name' => 'Delivered',
                'name_gujarati' => 'ડિલિવર થયું',
                'name_hindi' => 'डिलीवर हो गया',
                'description' => 'Order delivered to customer',
                'color' => '#22c55e',
                'icon' => 'check-badge',
                'is_mandatory' => true,
                'is_skippable' => false,
                'requires_photo' => false,
                'requires_approval' => false,
                'notify_customer' => true,
                'estimated_days' => 0,
                'assigned_role' => 'staff',
            ],
        ];

        // Store as a JSON template that will be used when creating tenant workflow stages
        // For now, we'll save this in a config or use it in TenantSeeder

        // Also create a system config to store default workflow template
        // This will be used when new tenants register

        config(['naari.default_workflow_stages' => $stages]);
    }

    /**
     * Get default workflow stages for creating tenant-specific workflow
     */
    public static function getDefaultStages(): array
    {
        return [
            ['stage_order' => 1, 'code' => 'ORDER_RECEIVED', 'name' => 'Order Received', 'name_gujarati' => 'ઓર્ડર પ્રાપ્ત', 'name_hindi' => 'ऑर्डर प्राप्त', 'color' => '#6366f1', 'icon' => 'clipboard-check', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => true, 'estimated_days' => 0, 'assigned_role' => 'staff'],
            ['stage_order' => 2, 'code' => 'MEASUREMENT_CONFIRMED', 'name' => 'Measurement Confirmed', 'name_gujarati' => 'માપ કન્ફર્મ', 'name_hindi' => 'माप कन्फर्म', 'color' => '#8b5cf6', 'icon' => 'ruler', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 1, 'assigned_role' => 'staff'],
            ['stage_order' => 3, 'code' => 'FABRIC_SELECTION', 'name' => 'Fabric Selection', 'name_gujarati' => 'કાપડ પસંદગી', 'name_hindi' => 'कपड़ा चयन', 'color' => '#a855f7', 'icon' => 'squares-2x2', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => true, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 2, 'assigned_role' => 'staff'],
            ['stage_order' => 4, 'code' => 'FABRIC_RECEIVED', 'name' => 'Fabric Received', 'name_gujarati' => 'કાપડ પ્રાપ્ત', 'name_hindi' => 'कपड़ा प्राप्त', 'color' => '#c026d3', 'icon' => 'inbox-arrow-down', 'is_mandatory' => true, 'is_skippable' => true, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 1, 'assigned_role' => 'staff'],
            ['stage_order' => 5, 'code' => 'CUTTING', 'name' => 'Cutting', 'name_gujarati' => 'કટિંગ', 'name_hindi' => 'कटिंग', 'color' => '#db2777', 'icon' => 'scissors', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 1, 'assigned_role' => 'worker'],
            ['stage_order' => 6, 'code' => 'CUTTING_COMPLETE', 'name' => 'Cutting Complete', 'name_gujarati' => 'કટિંગ પૂર્ણ', 'name_hindi' => 'कटिंग पूर्ण', 'color' => '#e11d48', 'icon' => 'check-circle', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => true, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 0, 'assigned_role' => 'worker'],
            ['stage_order' => 7, 'code' => 'EMBROIDERY_ASSIGNED', 'name' => 'Embroidery Assigned', 'name_gujarati' => 'ભરતકામ સોંપ્યું', 'name_hindi' => 'कढ़ाई सौंपी', 'color' => '#f97316', 'icon' => 'sparkles', 'is_mandatory' => false, 'is_skippable' => true, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 1, 'assigned_role' => 'manager'],
            ['stage_order' => 8, 'code' => 'EMBROIDERY_IN_PROGRESS', 'name' => 'Embroidery In Progress', 'name_gujarati' => 'ભરતકામ ચાલુ', 'name_hindi' => 'कढ़ाई जारी', 'color' => '#fb923c', 'icon' => 'cog', 'is_mandatory' => false, 'is_skippable' => true, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 5, 'assigned_role' => 'worker'],
            ['stage_order' => 9, 'code' => 'EMBROIDERY_COMPLETE', 'name' => 'Embroidery Complete', 'name_gujarati' => 'ભરતકામ પૂર્ણ', 'name_hindi' => 'कढ़ाई पूर्ण', 'color' => '#fbbf24', 'icon' => 'check-badge', 'is_mandatory' => false, 'is_skippable' => true, 'requires_photo' => true, 'requires_approval' => true, 'notify_customer' => false, 'estimated_days' => 0, 'assigned_role' => 'worker'],
            ['stage_order' => 10, 'code' => 'STITCHING_ASSIGNED', 'name' => 'Stitching Assigned', 'name_gujarati' => 'સિલાઈ સોંપી', 'name_hindi' => 'सिलाई सौंपी', 'color' => '#84cc16', 'icon' => 'user-plus', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 1, 'assigned_role' => 'manager'],
            ['stage_order' => 11, 'code' => 'STITCHING_IN_PROGRESS', 'name' => 'Stitching In Progress', 'name_gujarati' => 'સિલાઈ ચાલુ', 'name_hindi' => 'सिलाई जारी', 'color' => '#22c55e', 'icon' => 'cog', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 3, 'assigned_role' => 'worker'],
            ['stage_order' => 12, 'code' => 'STITCHING_COMPLETE', 'name' => 'Stitching Complete', 'name_gujarati' => 'સિલાઈ પૂર્ણ', 'name_hindi' => 'सिलाई पूर्ण', 'color' => '#10b981', 'icon' => 'check-circle', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => true, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 0, 'assigned_role' => 'worker'],
            ['stage_order' => 13, 'code' => 'FIRST_FITTING', 'name' => 'First Fitting', 'name_gujarati' => 'પ્રથમ ફિટિંગ', 'name_hindi' => 'पहली फिटिंग', 'color' => '#14b8a6', 'icon' => 'user-check', 'is_mandatory' => false, 'is_skippable' => true, 'requires_photo' => true, 'requires_approval' => true, 'notify_customer' => true, 'estimated_days' => 1, 'assigned_role' => 'staff'],
            ['stage_order' => 14, 'code' => 'ALTERATIONS', 'name' => 'Alterations', 'name_gujarati' => 'ફેરફાર', 'name_hindi' => 'बदलाव', 'color' => '#06b6d4', 'icon' => 'wrench', 'is_mandatory' => false, 'is_skippable' => true, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 2, 'assigned_role' => 'worker'],
            ['stage_order' => 15, 'code' => 'FINAL_FITTING', 'name' => 'Final Fitting', 'name_gujarati' => 'અંતિમ ફિટિંગ', 'name_hindi' => 'अंतिम फिटिंग', 'color' => '#0ea5e9', 'icon' => 'clipboard-check', 'is_mandatory' => false, 'is_skippable' => true, 'requires_photo' => true, 'requires_approval' => true, 'notify_customer' => true, 'estimated_days' => 1, 'assigned_role' => 'staff'],
            ['stage_order' => 16, 'code' => 'FINISHING', 'name' => 'Finishing', 'name_gujarati' => 'ફિનિશિંગ', 'name_hindi' => 'फिनिशिंग', 'color' => '#3b82f6', 'icon' => 'sparkles', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 1, 'assigned_role' => 'worker'],
            ['stage_order' => 17, 'code' => 'QUALITY_CHECK', 'name' => 'Quality Check', 'name_gujarati' => 'ક્વોલિટી ચેક', 'name_hindi' => 'क्वालिटी चेक', 'color' => '#6366f1', 'icon' => 'shield-check', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => true, 'requires_approval' => true, 'notify_customer' => false, 'estimated_days' => 1, 'assigned_role' => 'manager'],
            ['stage_order' => 18, 'code' => 'IRONING_PRESSING', 'name' => 'Ironing & Pressing', 'name_gujarati' => 'ઈસ્ત્રી', 'name_hindi' => 'इस्त्री', 'color' => '#8b5cf6', 'icon' => 'fire', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 1, 'assigned_role' => 'worker'],
            ['stage_order' => 19, 'code' => 'PACKING', 'name' => 'Packing', 'name_gujarati' => 'પેકિંગ', 'name_hindi' => 'पैकिंग', 'color' => '#a855f7', 'icon' => 'gift', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => true, 'requires_approval' => false, 'notify_customer' => false, 'estimated_days' => 0, 'assigned_role' => 'staff'],
            ['stage_order' => 20, 'code' => 'READY_FOR_DELIVERY', 'name' => 'Ready for Delivery', 'name_gujarati' => 'ડિલિવરી માટે તૈયાર', 'name_hindi' => 'डिलीवरी के लिए तैयार', 'color' => '#c026d3', 'icon' => 'truck', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => true, 'estimated_days' => 0, 'assigned_role' => 'staff'],
            ['stage_order' => 21, 'code' => 'DELIVERED', 'name' => 'Delivered', 'name_gujarati' => 'ડિલિવર થયું', 'name_hindi' => 'डिलीवर हो गया', 'color' => '#22c55e', 'icon' => 'check-badge', 'is_mandatory' => true, 'is_skippable' => false, 'requires_photo' => false, 'requires_approval' => false, 'notify_customer' => true, 'estimated_days' => 0, 'assigned_role' => 'staff'],
        ];
    }
}
